### ISSUE TITLE
Lazy loaded routes not translated

### ISSUE THREAD

**Issue by meeroslav** [Greentube/localize-router#3]
**Steps to reproduce**
Navigate to lazy loaded module.
Notice that deep links have been translated.
Click on one of the deep links

**Current behavior**
Router cannot find translated sub route.

**Expected behavior**
Router should successfully navigate user to lazy loaded sub route.

**Comment by Chuvisco88** [comment]
By lazy loaded module you mean routes which are added by .forChildren to the Router?

**Comment by meeroslav** [comment]
@Chuvisco88 Not necessarily. Entire containing module has to be lazy loaded:
```
{ path: 'someroute', loadChildren: 'path/to/some/route/my.module#MyModule'}
```
and of course, its routes are therefore loaded as child routes:
```
RouterModule.forChild([
  { path: '', component: MyModuleComponent }
])
```

**Comment by fulls1z3** [comment]
any updates on this issue?

**Comment by meeroslav** [comment]
Unfortunately didn't have time to focus on it. Sorry!

**Comment by fulls1z3** [comment]
No problem, I'm digging the plugin a little and gonna try to share the best available fallback methods to get it working with lazy loaded routes. Hope I can contribute more.

**Comment by meeroslav** [comment]
Thanks, any support is appreciated.

**Comment by jelenaDedskin** [comment]
Any update on this issue? I'm also having troubles with setting up localization for lazy loaded routes

**Comment by fulls1z3** [comment]
Hi @jelenaDedskin, I'm actually working on it due to my project needs. As far as I've seen the translation process takes place during init() method of the parser. And I've observed that root routes are processed this way, however lazy loaded routes are not.

I think I'll make sure what's happening at the background, and come up with a working PR soon.

**Comment by fulls1z3** [comment]
Finally I solved the issue. The problem is, `ng2-translate` returns an observable as the result of translation process. Lazy loaded routes can be translated (ex: http://mysite.com/en/account/login in english or http://mysite.com/fr/compte/entrer in french), but when you press reload button on the browser it redirects to http://mysite.com/en or http://mysite.com/fr.

This happens because when the app is initialized, route translation process has not been finished yet.

I could figure out a solution, only in the case when route translations for all languages are loaded during the app initialization.

However, it's practically impossible to merge this solution to the `localize-router`. It depends on `ng2-translate`.

If any ideas come up using `ng2-translate`, I'm ready to provide support and send all working code.

**Comment by meeroslav** [comment]
@fulls1z3 Do you have this code somewhere on github?

**Comment by fulls1z3** [comment]
@meeroslav still testing, hope I can upload it this weekend.

**Comment by fulls1z3** [comment]
Hi @meeroslav,

I've published the code on github. Please have a look at [i18n-router](https://github.com/nglibs/i18n-router) and [i18n-router-config-loader](https://github.com/nglibs/i18n-router-config-loader).

Didn't have an opportunity to write tests, but they will appear soon. Bugs will appear too :)

I also didn't forget to mention your project at the `Credits` section. And I have no words what a good reference and motivation `localize-router` has provided, and how can I thank to you.

I hope both projects can benefit from each other, and we can build something better in the future.

**Comment by fulls1z3** [comment]
Hi @meeroslav,

I've published the code on github. Please have a look at [i18n-router](https://github.com/nglibs/i18n-router) and [i18n-router-config-loader](https://github.com/nglibs/i18n-router-config-loader).

Didn't have an opportunity to write tests, but they will appear soon. Also didn't forget to mention localize-router at the `Credits` section.

**Comment by meeroslav** [comment]
@fulls1z3 I've seen you've took the different approach by avoiding `ng2-translate` so I understand why you've created separate package.
I will look more deeply later to see if there is something I might borrow as well :)

**Comment by CamusAran** [comment]
Any update on this?

**Comment by fulls1z3** [comment]
@meeroslav, @CamusAran
I suppose it's gonna be possible with `ngx-translate` too.

For this, route translations must be loaded during app initialization (until router@3.4.7).

With router@3.4.8, this behavior has been changed, I can't talk about it for sure.

They say this breaking (or failing) change will be reverted.

Anyway, will try to build a loader (for router@2.4.7) and let u know about that.
