### ISSUE TITLE
Don't set language prefix to url if there is only one locale 

### ISSUE THREAD

**Issue by thebarada** [Greentube/localize-router#34]
It will be great if url will not change if locales will have only one languag

**Comment by meeroslav** [comment]
It's a sensible request generally. 
However, if you have only one locale, why use `localize-router` in the first place?

**Comment by thebarada** [comment]
in my case, user can set up one or more langs in your profile
so, it is locales is dynamic

**Comment by Chuvisco88** [comment]
Well you still need to support `n` languages in this case, which means there should be multiple routes to the same page based on the language, right? :)

**Comment by thebarada** [comment]
but if user set up only one language, I think it will be more correctly if url will still without lang prefix :)

**Comment by Chuvisco88** [comment]
Okay, let's see it from the point of a route.
Let's say you have for example `/my-profile`. In english it will stay the same, for german it would be `/mein-profil` and in french it would be `/mon-profil`.
It does not matter if your user has only set French for example, as the other possibilities still can be used by other users.

Or could you give an example?

**Comment by thebarada** [comment]
Said `user`, I did not mean person that use application
I've mean user who set up you own application (like CMS)

**Comment by meeroslav** [comment]
Well, I can say that such functionality would most likely never be implemented because there are multiple unclear (and potentially breaking) scenarios:
* if user goes to `www.yoursite.com/person`  which language should the application be rendered in if this word exists in both German and English language?
* in order for application to apply translation and localization it has to load the correct translation file. If you provide only text e.g. `mon-profil`, we need to load all the languages to distinguish which one of them has this text (and then manually run route checking to see if it's even possible route) and then translate all the routes. All this while application is waiting in bootstrap loop. I can't even try to explain how (almost) impossible this is. Of course this only works in case scenario one does not happen
* no link sharing would be possible, unless two users share the same language
* etc.

Just from the top of my head, I'd say that quite a lot of good reasons to justify "annoyance" of language prefix.

**Comment by Chuvisco88** [comment]
Beside of that, if you as the user (setting up the application) decide to have just one language, why using `localize-router`? You decide the spectrum of languages so you should decide as well if the module is needed.

**Comment by thebarada** [comment]
@Chuvisco88 so, you suggest check number of languages before bootstrapping of application?

**Comment by meeroslav** [comment]
@thebarada Just checked the code quickly... There is a possibility to enable this functionality if only single locale is provided in the config. 
However, you have to understand that at the moment this has low priority and would require some additional changes which are planned only for the future version (spoiler: fully configurable `localize-router`).

**Comment by thebarada** [comment]
@meeroslav ok, I've see you
if you'll include this functionality to future version - it will be great)
will waiting for update)
