### ISSUE TITLE
Use this package without it overriding ngx-translate language settings

### ISSUE THREAD

**Issue by JochemKuijpers** [Greentube/localize-router#35]
I started using this package because I want to translate my routes. 
I have a method to decide which language to use for ngx-translate. Some other things depend on this as well, so it is not easily changed.

The module of this package seems to set the language earlier in it's `init` method than I am able to set the preferred language. It does so incorrectly, causing a 404 response on `/assets/i18n/en.json` (which does not exist!). This prevents my website from working correctly.

    uncaught exception: Response with status: 404 Not Found for URL: http://<snip>/assets/i18n/en.json

ngx-translate seems to recommend setting the language from AppComponent, as [they show in their README file](https://github.com/ngx-translate/core/tree/v6.0.0#2-init-the-translateservice-for-your-application). 

I'd like to be able to select the language this module should use, instead of it trying (and failing) to do it by itself. Thanks in advance!

**Comment by meeroslav** [comment]
Hi @JochemKuijpers,

`LocalizeRouter` sets the language on application init (APP_INITIALIZE loop) and translates the routes into target language before initial `NavigationStart` kicks in and AppComponent is initialized.
Unfortunately, this is mandatory as NavigationStart happens before AppComponent, and would otherwise load invalid route or break.

What I would suggest is to give you a possibility to pass your own function as a parameter to LocalizeRouter.forRoot function that would override standard language picking algorithm.

Would this work for you?

**Comment by JochemKuijpers** [comment]
Thanks for responding to my question.

Yes, definitely! This will work.

I suggest the function takes as parameters the current route and the suggested language by `localize-router`. This way, a function that returns the suggested language will have the default behaviour.

The reason I would like a reference to the current route, is because I'm basing the selected language upon various factors, including the path the user uses to load the webapp.

If you think something else is more appropriate yet still supports my use-case, that would be fine with me as well. 

Thanks again :)

**Comment by JochemKuijpers** [comment]
Any ETA of this fix? It's currently blocking for the next update of my website. Thanks!
