### ISSUE TITLE
LocalizeRouterModule.forChild doesn't work in lazy loaded modules

### ISSUE THREAD

**Issue by sanioky** [Greentube/localize-router#44]
I use ngx-translate and localize-router in my project.
I have MainModule where add ChildModule as lazy loaded.

const rotes: Routes = [
    {
        path: 'child',
        loadChildren: 'app/child/child.module#ChildModule '
    }
];

NgModule({
    imports: [
        TranslateModule.forRoot(...),
        RouterModule.forRoot(rotes),
        LocalizeRouterModule.forRoot(rotes)
    ]
})

Then in ChildModule I use forChild() method:
const rotes: Routes = [
    {
        path: '',
        component: ChildComponent,
    }
];
NgModule({
    imports: [
        TranslateModule.forChild(...),
        RouterModule.forChild(rotes),
        LocalizeRouterModule.forChild(rotes)
    ]
})

When I go to /child route in browser LocalizeRouter doesn't initializes ngx-translate core service with selected locales ( translate.use(lang) ). So I need to do it manually listening route changes.

It seems like forChild method doesn't provide TranslateService dependency

**Comment by meeroslav** [comment]
Not sure if I understood your problem exactly. Can you provide a minimal plunkr with this issue?
Correct route in your browser should be e.g. `en/child`. 

Note that at the moment lazy loading doesn't work for nested routes. If you have route like `lazy/lazy_child` if you navigate first to `lazy` and then to `lazy_child` everything will work. However if you go directly to `lazy/lazy_child` Router will report unknown route error, since child routes will not be translated before Route matching mechanism kicks in.

**Comment by sanioky** [comment]
You are right. 
I have routes like this en/register/step-1. 
Will you support such routes in future versions of your extension? 
Thank you in advance.

**Comment by meeroslav** [comment]
It's limited to current angular implementation. You can see request here: [https://github.com/angular/angular/issues/16282](https://github.com/angular/angular/issues/16282).

Until then, here is the issue on `localize-router` [https://github.com/Greentube/localize-router/issues/45](https://github.com/Greentube/localize-router/issues/45)

Does this "solve" your issue at the moment?

**Comment by meeroslav** [comment]
Closed due to duplication on #45
