### ISSUE TITLE
Ignoring Certain Routes

### ISSUE THREAD

**Issue by naaambo** [Greentube/localize-router#48]
Is there or will there be a method for ignoring routes? (For situations like Auth callback)

Thanks for the great library 👍

**Comment by meeroslav** [comment]
@naaambo Can you please provide more information (example)?

**Comment by naaambo** [comment]
For most routes prepending something like en-Gb is great. However in our system we need to send users back to a generic token handling endpoint which does not have the prefix. The SSO server uses a white-listing system so currently we'd have to register a callback endpoint per language.

So we'd like to be able to configure a route to not need the language prefix.

Thanks.

**Comment by meeroslav** [comment]
@naaambo So is this generic token handling endpoint (page?) only for redirection? If yes just assume it's `en/generic_whatever`. If not then there is some content, in which case what language should this generic page be shown in and why not allow users to see localized content?

**Comment by naaambo** [comment]
Sorry, I should have been clearer, this is essentially a redirect page and contains no content.

**Comment by meeroslav** [comment]
@naaambo If you can, provide a simple repo that shows your issue.

**Comment by meeroslav** [comment]
@naaambo I guess then route doesn't really matter and just use standard `navigateTo` to whatever your primary language is. At the moment there is no functionality that allows you to mark certain urls as non localizable. If following my guidelines it doesn't work for you, let me know and I'll try to add this feature as soon as possible.

**Comment by naaambo** [comment]
Afraid this is not an option, I might try looking at in the next few weeks and make a pull request if I get anywhere, Thanks for the help 🙂

**Comment by NKjoep** [comment]
👍  for this. It is useful also when you have to support some legacy urls. Think of the situation when you're rewriting your app and want to keep some url from the old website which wasn't localized or the language parameter was in a different position instead of the root.

| Old url | New url | Do not localize |
| :---         |     :--- | :--- |
| site.com/page1-en   | site.com/en/page1 | /page1 |
| site.com/home?lang=en   | site.com/en/ | /home |
| site.com/home?lang=de | site.com/de/ | /home | 
| site.com/something/path/par1-lang-par2 | site.com/lang/something/path?par&par2 | /something |
