### ISSUE TITLE
on page refresh localize doesn't reset.

### ISSUE THREAD

**Issue by premiumwd** [Greentube/localize-router#57]
I am using ngx-translate and a constructor translate with localizerouter to match and change the lang when someone selects a different language in dropdown. 

https://gist.github.com/premiumwd/9da2529037bc32e7aeaf243a9c3687ce

When I refresh page, if I selected a different language it doesn't go back to default lang. Any advice?

**Comment by NKjoep** [comment]
I think it happens because of the local storage. You have to manually force language with `LocalizeRouterService.changeLanguage(langStr)`.

But be careful, changeLanguage fn does this:

```js
    /**
     * Change language and navigate to translated route
     * @param lang
     */
    LocalizeRouterService.prototype.changeLanguage = function (lang) {
        var _this = this;
        if (lang !== this.parser.currentLang) {
            var rootSnapshot_1 = this.router.routerState.snapshot.root;
            this.parser.translateRoutes(lang).subscribe(function () {
                _this.router.navigateByUrl(_this.traverseRouteSnapshot(rootSnapshot_1));
            });
        }
    };
```

as you can see every time you change language it tries to reload navigate with the new language.

Hope it helps.

**Comment by meeroslav** [comment]
@premiumwd

I would have to debug your solution, but I think @NKjoep is right. Your latest language is set in localstorage and is probably overriding the setting in your NavComponent.

Since `LocalizeRouterService` is calling under the hood `TranslateService` (setting languages, setting default language, changing language) you don't need to (and shouldn't) do it on your own.

If localstorage is not needed please create a separate request issue.

**Comment by premiumwd** [comment]
@NKjoep I just need a hook into translate to reset when refresh, this is a bug I think should be addressed into updated version.
