### ISSUE TITLE
pipe localize does not handle "../"

### ISSUE THREAD

**Issue by MisterEffix** [Greentube/localize-router#76]
Angular routing allows us to use "../" syntax in a routerLink : 
- [routerLink]="['../']"
- [routerLink]="['../foo']"

But, it does not seems to work with " | localize".

**Comment by MisterEffix** [comment]
Any comments on this ?

**Comment by meeroslav** [comment]
That's odd, since it works on the demo project included in the solution and this scenario was tested.
Please check [https://github.com/Greentube/localize-router/blob/master/demo/cli/src/app/users/user/user.component.html](https://github.com/Greentube/localize-router/blob/master/demo/cli/src/app/users/user/user.component.html).

Can you tell me what is the url shown in browser footer when you hover the link?
Additionally, please let me know of your versions of Angular, LocalizeRouter and ngxTranslate.

**Comment by meeroslav** [comment]
Closed due to inactivity
